### PR TITLE
TECH-7085 dockerize sourcedive app

### PR DESCRIPTION
**Pull request by dataxerik**
The idea is to make it easier for a developer to setup the sourcedive project.

Technical Details
This uses Docker compose to setup the containers. There are two containers: a postgres and an app container. The postgre is the official postgre image, but sets some environment variables to create a database along with a user. The application container is a standard python3-alpine with commands to install the necessary modules.

QA
- [x] Follow along with the readme and see if you can get the application up and running.
- [x] Think about any flaws with the approach

### CODE REVIEW

**Comment by greglinch** [comment]
@dataxerik Sorry for the delay on this.

After executing `docker-compose build`, I got this (truncated)

```
Successfully built future oauthlib pycryptodomex pyjwkest pysolr python-gettext python-openid
Failed to build psycopg2
Installing collected packages: certifi, chardet, defusedxml, pytz, sqlparse, Django, django-debug-toolbar, future, idna, oauthlib, psycopg2, pycryptodomex, urllib3, requests, six, pyjwkest, PyJWT, pysolr, python-gettext, python-openid, python3-openid, requests-oauthlib, social-auth-core, python-social-auth, social-auth-app-django
    Running setup.py install for psycopg2: started
    Running setup.py install for psycopg2: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-r_e2uv4y/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-r_e2uv4y/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-egqef9cc/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-r_e2uv4y/psycopg2/
    Complete output (62 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/psycopg2
    copying lib/pool.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/sql.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/extensions.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/_json.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/tz.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/psycopg1.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/__init__.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/errorcodes.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/_ipaddress.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/_range.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/extras.py -> build/lib.linux-x86_64-3.8/psycopg2
    creating build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_psycopg2_dbapi20.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_bugX000.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_green.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/dbapi20.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_cancel.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_ipaddress.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_types_basic.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_async.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/testutils.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/testconfig.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_errcodes.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_fast_executemany.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_extras_dictcursor.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_quote.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_dates.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_module.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_connection.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/__init__.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_notify.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_async_keyword.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_lobject.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_with.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_cursor.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_transaction.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/dbapi20_tpc.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_types_extras.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_bug_gc.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_copy.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_sql.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_replication.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    running build_ext
    building 'psycopg2._psycopg' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/psycopg
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -DPSYCOPG_DEFAULT_PYDATETIME=1 -DPSYCOPG_VERSION="2.7.3.1 (dt dec pq3 ext lo64)" -DPG_VERSION_NUM=110500 -DHAVE_LO64=1 -I/usr/local/include/python3.8 -I. -I/usr/include -I/usr/include/postgresql/server -c psycopg/psycopgmodule.c -o build/temp.linux-x86_64-3.8/psycopg/psycopgmodule.o -Wdeclaration-after-statement
    psycopg/psycopgmodule.c: In function 'psyco_is_main_interp':
    psycopg/psycopgmodule.c:685:18: error: dereferencing pointer to incomplete type 'PyInterpreterState' {aka 'struct _is'}
         while (interp->next)
                      ^~
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-r_e2uv4y/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-r_e2uv4y/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-egqef9cc/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
ERROR: Service 'app' failed to build: The command '/bin/sh -c apk add --no-cache postgresql-libs &&  apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev &&  python3 -m pip install -r requirements.txt --no-cache-dir &&  apk --purge del .build-deps' returned a non-zero code: 1
```

**Comment by greglinch** [comment]
@dataxerik I ran `docker-compose build --no-cache` and got this — looks the same:

```
Successfully built future oauthlib pycryptodomex pyjwkest pysolr python-gettext python-openid
Failed to build psycopg2
Installing collected packages: certifi, chardet, defusedxml, pytz, sqlparse, Django, django-debug-toolbar, future, idna, oauthlib, psycopg2, pycryptodomex, urllib3, requests, six, pyjwkest, PyJWT, pysolr, python-gettext, python-openid, requests-oauthlib, python3-openid, social-auth-core, python-social-auth, social-auth-app-django
    Running setup.py install for psycopg2: started
    Running setup.py install for psycopg2: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1svv5w4j/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1svv5w4j/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-auft13f6/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-1svv5w4j/psycopg2/
    Complete output (62 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/psycopg2
    copying lib/pool.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/sql.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/extensions.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/_json.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/tz.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/psycopg1.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/__init__.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/errorcodes.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/_ipaddress.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/_range.py -> build/lib.linux-x86_64-3.8/psycopg2
    copying lib/extras.py -> build/lib.linux-x86_64-3.8/psycopg2
    creating build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_psycopg2_dbapi20.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_bugX000.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_green.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/dbapi20.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_cancel.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_ipaddress.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_types_basic.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_async.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/testutils.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/testconfig.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_errcodes.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_fast_executemany.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_extras_dictcursor.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_quote.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_dates.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_module.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_connection.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/__init__.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_notify.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_async_keyword.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_lobject.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_with.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_cursor.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_transaction.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/dbapi20_tpc.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_types_extras.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_bug_gc.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_copy.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_sql.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    copying tests/test_replication.py -> build/lib.linux-x86_64-3.8/psycopg2/tests
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    running build_ext
    building 'psycopg2._psycopg' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/psycopg
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -DPSYCOPG_DEFAULT_PYDATETIME=1 -DPSYCOPG_VERSION="2.7.3.1 (dt dec pq3 ext lo64)" -DPG_VERSION_NUM=110600 -DHAVE_LO64=1 -I/usr/local/include/python3.8 -I. -I/usr/include -I/usr/include/postgresql/server -c psycopg/psycopgmodule.c -o build/temp.linux-x86_64-3.8/psycopg/psycopgmodule.o -Wdeclaration-after-statement
    psycopg/psycopgmodule.c: In function 'psyco_is_main_interp':
    psycopg/psycopgmodule.c:685:18: error: dereferencing pointer to incomplete type 'PyInterpreterState' {aka 'struct _is'}
         while (interp->next)
                      ^~
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1svv5w4j/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1svv5w4j/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-auft13f6/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
ERROR: Service 'app' failed to build: The command '/bin/sh -c apk add --no-cache postgresql-libs &&  apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev &&  python3 -m pip install -r requirements.txt --no-cache-dir &&  apk --purge del .build-deps' returned a non-zero code: 1
```

**Comment by dbarbar** [comment]
https://github.com/psycopg/psycopg2/issues/858

Looks like that version of psycopg2 isn't compatible with python 3.8. Newer versions are however. So either upgrade that or downgrade python to 3.7.

https://pypi.org/project/psycopg2/#history

**Comment by greglinch** [comment]
Thanks, @dbarbar!

@dataxerik I upgraded pyscopg2 in `requirements.txt` to `psycopg2==2.8.4`, ran the `build` and `up` commands and, on the `up` command, got the following — also related to postgres.

```
db_1   | server started
db_1   | CREATE DATABASE
db_1   |
db_1   |
db_1   | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1   |
db_1   | 2019-12-12 18:22:59.292 UTC [43] LOG:  received fast shutdown request
db_1   | waiting for server to shut down....2019-12-12 18:22:59.293 UTC [43] LOG:  aborting any active transactions
db_1   | 2019-12-12 18:22:59.296 UTC [43] LOG:  background worker "logical replication launcher" (PID 50) exited with exit code 1
db_1   | 2019-12-12 18:22:59.296 UTC [45] LOG:  shutting down
db_1   | 2019-12-12 18:22:59.311 UTC [43] LOG:  database system is shut down
db_1   |  done
db_1   | server stopped
db_1   |
db_1   | PostgreSQL init process complete; ready for start up.
db_1   |
db_1   | 2019-12-12 18:22:59.405 UTC [1] LOG:  starting PostgreSQL 12.0 (Debian 12.0-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
db_1   | 2019-12-12 18:22:59.405 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1   | 2019-12-12 18:22:59.405 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1   | 2019-12-12 18:22:59.407 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1   | 2019-12-12 18:22:59.417 UTC [61] LOG:  database system was shut down at 2019-12-12 18:22:59 UTC
db_1   | 2019-12-12 18:22:59.421 UTC [1] LOG:  database system is ready to accept connections
app_1  | Watching for file changes with StatReloader
app_1  | Exception in thread django-main-thread:
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
app_1  |     self.connect()
app_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 195, in connect
app_1  |     self.connection = self.get_new_connection(conn_params)
app_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
app_1  |     connection = Database.connect(**conn_params)
app_1  |   File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
app_1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
app_1  | psycopg2.OperationalError: could not connect to server: Connection refused
app_1  | 	Is the server running on host "localhost" (127.0.0.1) and accepting
app_1  | 	TCP/IP connections on port 5432?
app_1  | could not connect to server: Address not available
app_1  | 	Is the server running on host "localhost" (::1) and accepting
app_1  | 	TCP/IP connections on port 5432?
app_1  |
app_1  |
app_1  | The above exception was the direct cause of the following exception:
app_1  |
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
app_1  |     self.run()
app_1  |   File "/usr/local/lib/python3.8/threading.py", line 870, in run
app_1  |     self._target(*self._args, **self._kwargs)
app_1  |   File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 54, in wrapper
app_1  |     fn(*args, **kwargs)
app_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 120, in inner_run
app_1  |     self.check_migrations()
app_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 453, in check_migrations
app_1  |     executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
app_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
app_1  |     self.loader = MigrationLoader(self.connection)
app_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 49, in __init__
app_1  |     self.build_graph()
app_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 212, in build_graph
app_1  |     self.applied_migrations = recorder.applied_migrations()
app_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
app_1  |     if self.has_table():
app_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 56, in has_table
app_1  |     return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
app_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 256, in cursor
app_1  |     return self._cursor()
app_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 233, in _cursor
app_1  |     self.ensure_connection()
app_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
app_1  |     self.connect()
app_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
app_1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
app_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
app_1  |     self.connect()
app_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 195, in connect
app_1  |     self.connection = self.get_new_connection(conn_params)
app_1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
app_1  |     connection = Database.connect(**conn_params)
app_1  |   File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
app_1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
app_1  | django.db.utils.OperationalError: could not connect to server: Connection refused
app_1  | 	Is the server running on host "localhost" (127.0.0.1) and accepting
app_1  | 	TCP/IP connections on port 5432?
app_1  | could not connect to server: Address not available
app_1  | 	Is the server running on host "localhost" (::1) and accepting
app_1  | 	TCP/IP connections on port 5432?
app_1  |
```

**Comment by greglinch** [comment]
@dataxerik I fixed this by updating my private settings locally to match the updated README. Oops!

Currently getting this when trying to log in:

```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8080/admin/login/?next=/admin/

Django Version: 2.2.4
Python Version: 3.8.0
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'sources.apps.SourcesConfig',
 'social_django',
 'debug_toolbar']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware']



Traceback:

File "/usr/local/lib/python3.8/site-packages/openid/oidutil.py" in importElementTree
  112.                 ElementTree.XML('<unused/>')

File "/usr/local/lib/python3.8/site-packages/defusedxml/common.py" in fromstring
  113.         parser = DefusedXMLParser(target=_TreeBuilder(),

File "/usr/local/lib/python3.8/site-packages/defusedxml/ElementTree.py" in __init__
  68.         _XMLParser.__init__(self, html, target, encoding)

During handling of the above exception (__init__() takes 1 positional argument but 4 were given), another exception occurred:

File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  44.         response = view_func(request, *args, **kwargs)

File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py" in login
  383.             **self.each_context(request),

File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py" in each_context
  302.             'available_apps': self.get_app_list(request),

File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py" in get_app_list
  474.         app_dict = self._build_app_dict(request)

File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py" in _build_app_dict
  419.             has_module_perms = model_admin.has_module_permission(request)

File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py" in has_module_permission
  537.         return request.user.has_module_perms(self.opts.app_label)

File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/models.py" in has_module_perms
  423.         return _user_has_module_perms(self, module)

File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/models.py" in _user_has_module_perms
  193.     for backend in auth.get_backends():

File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/__init__.py" in get_backends
  38.     return _get_backends(return_tuples=False)

File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/__init__.py" in _get_backends
  27.         backend = load_backend(backend_path)

File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/__init__.py" in load_backend
  21.     return import_string(path)()

File "/usr/local/lib/python3.8/site-packages/django/utils/module_loading.py" in import_string
  17.     module = import_module(module_path)

File "/usr/local/lib/python3.8/importlib/__init__.py" in import_module
  127.     return _bootstrap._gcd_import(name[level:], package, level)

File "<frozen importlib._bootstrap>" in _gcd_import
  1014. <source code not available>

File "<frozen importlib._bootstrap>" in _find_and_load
  991. <source code not available>

File "<frozen importlib._bootstrap>" in _find_and_load_unlocked
  975. <source code not available>

File "<frozen importlib._bootstrap>" in _load_unlocked
  671. <source code not available>

File "<frozen importlib._bootstrap_external>" in exec_module
  783. <source code not available>

File "<frozen importlib._bootstrap>" in _call_with_frames_removed
  219. <source code not available>

File "/usr/local/lib/python3.8/site-packages/social/backends/google.py" in <module>
  1. from social_core.backends.google import BaseGoogleAuth, BaseGoogleOAuth2API, \

File "/usr/local/lib/python3.8/site-packages/social_core/backends/google.py" in <module>
  6. from .open_id import OpenIdAuth

File "/usr/local/lib/python3.8/site-packages/social_core/backends/open_id.py" in <module>
  6. from openid.consumer.consumer import Consumer, SUCCESS, CANCEL, FAILURE

File "/usr/local/lib/python3.8/site-packages/openid/consumer/consumer.py" in <module>
  196. from openid.consumer.discover import discover, OpenIDServiceEndpoint, \

File "/usr/local/lib/python3.8/site-packages/openid/consumer/discover.py" in <module>
  22. from openid.yadis.etxrd import nsTag, XRDSError, XRD_NS_2_0

File "/usr/local/lib/python3.8/site-packages/openid/yadis/etxrd.py" in <module>
  31. SafeElementTree = importSafeElementTree()

File "/usr/local/lib/python3.8/site-packages/openid/oidutil.py" in importSafeElementTree
  83.         return importElementTree(module_names)

File "/usr/local/lib/python3.8/site-packages/openid/oidutil.py" in importElementTree
  117.                     'Not using ElementTree library %r because it failed to '

Exception Type: TypeError at /admin/login/
Exception Value: not enough arguments for format string
```

**Review by greglinch — APPROVED** [review]

**Pull request merged**
